### ISSUE TITLE
Generating nested DTOs

### ISSUE THREAD

**Issue by atymic** [atymic/json2dto#2]
It would be good if the tool could automatically generate nested DTOs. Might be better suited to the CLI version, see #1

**Comment by mfn** [comment]
Just making a comment that I'm looking forward to this, that would be pretty useful!

**Comment by atymic** [comment]
I've got this mostly done 🎉 
Currently no error handling and such, need to write the CLI tool as well.

@mfn, quick question, how do you structure your DTO folder?

Here's an example generation: 

![image](https://user-images.githubusercontent.com/50683531/72217005-d987e480-357c-11ea-8484-34be0377cccd.png)
![image](https://user-images.githubusercontent.com/50683531/72217013-f8867680-357c-11ea-90ca-afcd79e46e4d.png)

**Comment by mfn** [comment]
I nest them using namespaces, thus using directories.

Also, from your screenshots, these DTOs won't work. Nested DTOs require an *absolute / un-imported* name qualifier (a [performance] limitation of the current implementation).

**Comment by atymic** [comment]
> I nest them using namespaces, thus using directories.

Ok, sweet (that's what the generator will do).

> Also, from your screenshots, these DTOs won't work. Nested DTOs require an absolute / un-imported name qualifier (a [performance] limitation of the current implementation).

From reading the docs, I took that to mean that only applied to collections (as `Authors` for example uses the FQCN). Will update that for normal nested as well :)

**Comment by atymic** [comment]
@mfn 

Beta version of the CLI has been released `atymic/json2dto` :)
It includes support for generating nested DTOs. No tests yet, so there might be some bugs so make sure you have git/backup :)

I also updated the site to support generating nested DTOs

**Comment by mfn** [comment]
Nice, gave it a spin, impressive result!

**Comment by atymic** [comment]
Gonna close this now and it seems to be working. 
Tests to come :)
