### ISSUE TITLE
Nested DTO generation is blocked by CORS

### ISSUE THREAD

**Issue by dennisvandalen** [atymic/json2dto#37]
When generating a nested DTO on json2dto.atymic.dev you get a generic error: `Failed to generate DTO`.

Upon inspecting in the console it seems to be a CORS issue. 

```
Access to XMLHttpRequest at 'https://json2dto-max7gzuovq-uc.a.run.app/' from origin 'https://json2dto.atymic.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The headers are being added in the source so I can't further debug this. Maybe it is some setting on the hosting somehow?

**Comment by atymic** [comment]
Fixed, was 500ing but couldn't see the stack trace due to cors :)
